/* Header file for custom costmap plugin which creates a costmap layer marking the path generated by the model */


#ifndef PATH_LAYER_HPP_
#define PATH_LAYER_HPP_

#include "rclcpp/rclcpp.hpp"
#include "nav2_costmap_2d/layer.hpp"
#include "nav2_costmap_2d/layered_costmap.hpp"

namespace nav2_path_costmap_plugin {

    class PathLayer : public nav2_costmap_2d::Layer {
    public:
        PathLayer();

        virtual void onInitialize();
        virtual void updateBounds(
            double robot_x, double robot_y, double robot_yaw, double * min_x,
            double * min_y,
            double * max_x,
            double * max_y);

        virtual void updateCosts(
            nav2_costmap_2d::Costmap2D & master_grid,
            int min_i, int min_j, int max_i, int max_j);

        virtual void reset() {
            return;
        }

        virtual void onFootprintChanged();

        virtual bool isClearable() {return false;}

    private:
        int temp;
    };
}

#endif